# Generated by Django 3.0.8 on 2020-10-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
