# Generated by Django 3.0.8 on 2020-10-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_records', '0002_fileinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='admin_user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
